apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-reverseproxy
  name: udagram-reverseproxy
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-reverseproxy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-reverseproxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}



# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     service: udagram-reverseproxy
#   name: udagram-reverseproxy-svc
# spec:
#   ports:
#   - name: "8080"
#     port: 8080
#     targetPort: 8080
#   selector:
#     service: udagram-reverseproxy

