apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: ridwan05/udagram-api-feed
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRES_PASSWORD
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DOCKER_USERNAME
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DOCKER_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: POSTGRES_HOST
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: AWS_PROFILE
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: AWS_BUCKET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: JWT_SECRET
      restartPolicy: Always

      


        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "1024Mi"
        #     cpu: "500m"

        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 3
        #   periodSeconds: 3




# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   labels:
#     service: udagram-api-feed
#   name: udagram-api-feed
# spec:
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         service: udagram-api-feed
#     spec:
#       containers:
#       - image: ridwan05/udagram-api-feed
#         name: udagram-api-feed
#         imagePullPolicy: Always          
#         resources:
#           requests:
#             memory: "64Mi"
#             cpu: "250m"
#           limits:
#             memory: "1024Mi"
#             cpu: "500m"       
#         ports:
#         - containerPort: 8080
#       restartPolicy: Always





