apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: ridwan05/udagram-api-user
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3



# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   labels:
#     service: udagram-api-user
#   name: udagram-api-user
# spec:
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         service: udagram-api-user
#     spec:
#       containers:
#       - image: ridwan05/udagram-api-user
#         name: udagram-api-user
#         imagePullPolicy: Always          
#         resources:
#           requests:
#             memory: "64Mi"
#             cpu: "250m"
#           limits:
#             memory: "1024Mi"
#             cpu: "500m"       
#         ports:
#         - containerPort: 8080
#       restartPolicy: Always




